// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "sta-20190501135714--hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://sta-20190501135714--hostingbucket.s3-website-us-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-west-2:3c48cc21-237c-41b5-9970-c7679f2c92fa",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_mbpVINoop",
    "aws_user_pools_web_client_id": "6q1lc5g4kdnc29p521m5vp5thn"
};


export default awsmobile;
